// AUTO-GENERATED CONTENT NOTE:
// The CHARACTERS / MARKS / QUALITIES / UNLOCKS data below was transcribed from the reference
// chart (image.png) — every cell's item name was read from the chart and every cell's quality
// colour was sampled from the chart's own pixels and matched against its KEY palette.
// Wiki filenames were verified against https://bindingofisaacrebirth.wiki.gg (build time only).
// This module is the single source of truth for both the app and scripts/scrape-assets.ts.

export type QualityKey =
  | "q4" | "q3" | "q2" | "q1" | "q0"
  | "trinket" | "coop" | "character" | "feature" | "consumable";

export interface Character {
  id: string;
  label: string;
  /** Wiki file name — used by scripts/scrape-assets.ts only, never at runtime. */
  wikiFile: string;
  tainted: boolean;
}

export interface Mark {
  id: string;
  label: string;
  /** Boss portrait shown in the row header. */
  bossFile: string;
  /** In-game completion-mark icon, shown in Completion Mark mode. */
  markFile: string;
}

export interface Unlock {
  item: string;
  wikiFile: string;
  quality: QualityKey;
}

export type CharId = (typeof CHARACTERS)[number]["id"];
export type MarkId = (typeof MARKS)[number]["id"];

/** Sparse: UNLOCKS[charId]?.[markId] — a missing entry is a NO UNLOCK cell. */
export type UnlockMatrix = Partial<Record<string, Partial<Record<string, Unlock>>>>;

/** User completion state per cell. */
export type CellState = 0 | 1 | 2; // 0 none · 1 normal · 2 hard

/** Columns, in reference-chart order: 17 untainted then 17 tainted. */
export const CHARACTERS: Character[] = [
  { id: "isaac",          label: "Isaac",              wikiFile: "Character_Isaac_icon.png",                  tainted: false },
  { id: "magdalene",      label: "Magdalene",          wikiFile: "Character_Magdalene_icon.png",              tainted: false },
  { id: "cain",           label: "Cain",               wikiFile: "Character_Cain_icon.png",                   tainted: false },
  { id: "judas",          label: "Judas",              wikiFile: "Character_Judas_icon.png",                  tainted: false },
  { id: "blue_baby",      label: "Blue Baby",          wikiFile: "Character_???_icon.png",                    tainted: false },
  { id: "eve",            label: "Eve",                wikiFile: "Character_Eve_icon.png",                    tainted: false },
  { id: "samson",         label: "Samson",             wikiFile: "Character_Samson_icon.png",                 tainted: false },
  { id: "azazel",         label: "Azazel",             wikiFile: "Character_Azazel_icon.png",                 tainted: false },
  { id: "lazarus",        label: "Lazarus",            wikiFile: "Character_Lazarus_icon.png",                tainted: false },
  { id: "eden",           label: "Eden",               wikiFile: "Character_Eden_icon.png",                   tainted: false },
  { id: "the_lost",       label: "The Lost",           wikiFile: "Character_The_Lost_icon.png",               tainted: false },
  { id: "lilith",         label: "Lilith",             wikiFile: "Character_Lilith_icon.png",                 tainted: false },
  { id: "keeper",         label: "Keeper",             wikiFile: "Character_Keeper_icon.png",                 tainted: false },
  { id: "apollyon",       label: "Apollyon",           wikiFile: "Character_Apollyon_icon.png",               tainted: false },
  { id: "the_forgotten",  label: "The Forgotten",      wikiFile: "Character_The_Forgotten_icon.png",          tainted: false },
  { id: "bethany",        label: "Bethany",            wikiFile: "Character_Bethany_icon.png",                tainted: false },
  { id: "jacob_esau",     label: "Jacob & Esau",       wikiFile: "Character_Jacob_and_Esau_icon.png",         tainted: false },
  { id: "t_isaac",        label: "Tainted Isaac",      wikiFile: "Character_Tainted_Isaac_icon.png",          tainted: true },
  { id: "t_magdalene",    label: "Tainted Magdalene",  wikiFile: "Character_Tainted_Magdalene_icon.png",      tainted: true },
  { id: "t_cain",         label: "Tainted Cain",       wikiFile: "Character_Tainted_Cain_icon.png",           tainted: true },
  { id: "t_judas",        label: "Tainted Judas",      wikiFile: "Character_Tainted_Judas_icon.png",          tainted: true },
  { id: "t_blue_baby",    label: "Tainted Blue Baby",  wikiFile: "Character_Tainted_???_icon.png",            tainted: true },
  { id: "t_eve",          label: "Tainted Eve",        wikiFile: "Character_Tainted_Eve_icon.png",            tainted: true },
  { id: "t_samson",       label: "Tainted Samson",     wikiFile: "Character_Tainted_Samson_icon.png",         tainted: true },
  { id: "t_azazel",       label: "Tainted Azazel",     wikiFile: "Character_Tainted_Azazel_icon.png",         tainted: true },
  { id: "t_lazarus",      label: "Tainted Lazarus",    wikiFile: "Character_Tainted_Lazarus_icon.png",        tainted: true },
  { id: "t_eden",         label: "Tainted Eden",       wikiFile: "Character_Tainted_Eden_icon.png",           tainted: true },
  { id: "t_lost",         label: "Tainted Lost",       wikiFile: "Character_Tainted_Lost_icon.png",           tainted: true },
  { id: "t_lilith",       label: "Tainted Lilith",     wikiFile: "Character_Tainted_Lilith_icon.png",         tainted: true },
  { id: "t_keeper",       label: "Tainted Keeper",     wikiFile: "Character_Tainted_Keeper_icon.png",         tainted: true },
  { id: "t_apollyon",     label: "Tainted Apollyon",   wikiFile: "Character_Tainted_Apollyon_icon.png",       tainted: true },
  { id: "t_forgotten",    label: "Tainted Forgotten",  wikiFile: "Character_Tainted_Forgotten_icon.png",      tainted: true },
  { id: "t_bethany",      label: "Tainted Bethany",    wikiFile: "Character_Tainted_Bethany_icon.png",        tainted: true },
  { id: "t_jacob",        label: "Tainted Jacob",      wikiFile: "Character_Tainted_Jacob_icon.png",          tainted: true },
];

/** Rows, in reference-chart order. The chart's meta "All Marks" row is not a tracked mark. */
export const MARKS: Mark[] = [
  { id: "moms_heart",      label: "Mom's Heart",      bossFile: "Boss_Mom's_Heart_portrait.png",   markFile: "Completion_Heart.png" },
  { id: "isaac",           label: "Isaac",            bossFile: "Boss_Isaac_portrait.png",         markFile: "Completion_Cathedral.png" },
  { id: "blue_baby",       label: "??? (Blue Baby)",  bossFile: "Boss_???_portrait.png",           markFile: "Completion_Chest.png" },
  { id: "satan",           label: "Satan",            bossFile: "Boss_Satan_portrait.png",         markFile: "Completion_Sheol.png" },
  { id: "lamb",            label: "The Lamb",         bossFile: "Boss_The_Lamb_portrait.png",      markFile: "Completion_DarkRoom.png" },
  { id: "mega_satan",      label: "Mega Satan",       bossFile: "Boss_Mega_Satan_portrait.png",    markFile: "Completion_Brimstone.png" },
  { id: "boss_rush",       label: "Boss Rush",        bossFile: "Boss_Rush_Icon.png",              markFile: "Completion_BossRush.png" },
  { id: "hush",            label: "Hush",             bossFile: "Boss_Hush_portrait.png",          markFile: "Completion_BlueWomb.png" },
  { id: "delirium",        label: "Delirium",         bossFile: "Boss_Delirium_portrait.png",      markFile: "Completion_Void.png" },
  { id: "mother",          label: "Mother",           bossFile: "Boss_Mother_portrait.png",        markFile: "Completion_Mother.png" },
  { id: "beast",           label: "The Beast",        bossFile: "Boss_The_Beast_portrait.png",     markFile: "Completion_Beast.png" },
  { id: "ultra_greed",     label: "Ultra Greed",      bossFile: "Boss_Ultra_Greed_ingame.png",     markFile: "Completion_Greed.png" },
  { id: "ultra_greedier",  label: "Ultra Greedier",   bossFile: "Boss_Ultra_Greedier_ingame.png",  markFile: "Completion_Greed.png" },
];

/** The chart's KEY. Colours are sampled straight out of image.png's key swatches. */
export const QUALITIES: Record<QualityKey, { label: string; color: string }> = {
  q4:         { label: "Quality 4",    color: "#fad000" },
  q3:         { label: "Quality 3",    color: "#cb82ca" },
  q2:         { label: "Quality 2",    color: "#7cb7d1" },
  q1:         { label: "Quality 1",    color: "#95d062" },
  q0:         { label: "Quality 0",    color: "#c2c2c2" },
  trinket:    { label: "Trinket",      color: "#d86564" },
  coop:       { label: "Co-op Baby",   color: "#434343" },
  character:  { label: "Character",    color: "#000000" },
  feature:    { label: "Game Feature", color: "#491030" },
  consumable: { label: "Consumables",  color: "#c88d54" },
};

/**
 * Per-cell unlock guide, transcribed from image.png.
 *
 * Where the chart merges a block of rows into one cell, every row in that block carries the
 * same unlock here (the game grants it for whichever of those bosses you beat first):
 *   · Tainted characters, Isaac / ??? / Satan / The Lamb  → that character's trinket
 *   · Tainted characters, Boss Rush + Hush                → that character's Soul stone
 */
export const UNLOCKS: UnlockMatrix = {
  isaac: {
    moms_heart:      { item: "Lost Baby",               wikiFile: "010_baby_lost.png",                             quality: "coop" },
    isaac:           { item: "Isaac's Tears",           wikiFile: "Collectible_Isaac's_Tears_icon.png",            quality: "q1" },
    blue_baby:       { item: "The D20",                 wikiFile: "Collectible_D20_icon.png",                      quality: "q2" },
    satan:           { item: "Mom's Knife",             wikiFile: "Collectible_Mom's_Knife_icon.png",              quality: "q4" },
    lamb:            { item: "Missing Poster",          wikiFile: "Trinket_Missing_Poster_icon.png",               quality: "trinket" },
    mega_satan:      { item: "Cry Baby",                wikiFile: "032_baby_cry.png",                              quality: "coop" },
    boss_rush:       { item: "Isaac's Head",            wikiFile: "Trinket_Isaac's_Head_icon.png",                 quality: "trinket" },
    hush:            { item: "Fart Baby",               wikiFile: "Collectible_Farting_Baby_icon.png",             quality: "q1" },
    delirium:        { item: "D Infinity",              wikiFile: "Collectible_D_infinity_icon.png",               quality: "q4" },
    mother:          { item: "Meat Cleaver",            wikiFile: "Collectible_Meat_Cleaver_icon.png",             quality: "q1" },
    beast:           { item: "Options?",                wikiFile: "Collectible_Options?_icon.png",                 quality: "q2" },
    ultra_greed:     { item: "Lil Chest",               wikiFile: "Collectible_Lil_Chest_icon.png",                quality: "q2" },
    ultra_greedier:  { item: "D1",                      wikiFile: "Collectible_D1_icon.png",                       quality: "q2" },
  },
  magdalene: {
    moms_heart:      { item: "Cute Baby",               wikiFile: "011_baby_cute.png",                             quality: "coop" },
    isaac:           { item: "The Relic",               wikiFile: "Collectible_The_Relic_icon.png",                quality: "q3" },
    blue_baby:       { item: "Celtic Cross",            wikiFile: "Collectible_Celtic_Cross_icon.png",             quality: "q1" },
    satan:           { item: "Guardian Angel",          wikiFile: "Collectible_Guardian_Angel_icon.png",           quality: "q2" },
    lamb:            { item: "Maggy's Faith",           wikiFile: "Trinket_Maggy's_Faith_icon.png",                quality: "trinket" },
    mega_satan:      { item: "Red Baby",                wikiFile: "028_baby_red.png",                              quality: "coop" },
    boss_rush:       { item: "Maggy's Bow",             wikiFile: "Collectible_Maggy's_Bow_icon.png",              quality: "q2" },
    hush:            { item: "Purity",                  wikiFile: "Collectible_Purity_icon.png",                   quality: "q3" },
    delirium:        { item: "Eucharist",               wikiFile: "Collectible_Eucharist_icon.png",                quality: "q3" },
    mother:          { item: "Yuck Heart",              wikiFile: "Collectible_Yuck_Heart_icon.png",               quality: "q1" },
    beast:           { item: "Candy Heart",             wikiFile: "Collectible_Candy_Heart_icon.png",              quality: "q1" },
    ultra_greed:     { item: "Censer",                  wikiFile: "Collectible_Censer_icon.png",                   quality: "q3" },
    ultra_greedier:  { item: "Glyph of Balance",        wikiFile: "Collectible_Glyph_of_Balance_icon.png",         quality: "q2" },
  },
  cain: {
    moms_heart:      { item: "Glass Baby",              wikiFile: "014_baby_glass.png",                            quality: "coop" },
    isaac:           { item: "Sack of Pennies",         wikiFile: "Collectible_Sack_of_Pennies_icon.png",          quality: "q1" },
    blue_baby:       { item: "Cain's Eye",              wikiFile: "Trinket_Cain's_Eye_icon.png",                   quality: "trinket" },
    satan:           { item: "Bomb Bag",                wikiFile: "Collectible_Bomb_Bag_icon.png",                 quality: "q2" },
    lamb:            { item: "Abel",                    wikiFile: "Collectible_Abel_icon.png",                     quality: "q0" },
    mega_satan:      { item: "Green Baby",              wikiFile: "035_baby_green.png",                            quality: "coop" },
    boss_rush:       { item: "Cain's Other Eye",        wikiFile: "Collectible_Cain's_Other_Eye_icon.png",         quality: "q2" },
    hush:            { item: "D12",                     wikiFile: "Collectible_D12_icon.png",                      quality: "q1" },
    delirium:        { item: "Silver Dollar",           wikiFile: "Trinket_Silver_Dollar_icon.png",                quality: "trinket" },
    mother:          { item: "Guppy's Eye",             wikiFile: "Collectible_Guppy's_Eye_icon.png",              quality: "q2" },
    beast:           { item: "A Pound of Flesh",        wikiFile: "Collectible_A_Pound_of_Flesh_icon.png",         quality: "q1" },
    ultra_greed:     { item: "Evil Eye",                wikiFile: "Collectible_Evil_Eye_icon.png",                 quality: "q2" },
    ultra_greedier:  { item: "Sack of Sacks",           wikiFile: "Collectible_Sack_of_Sacks_icon.png",            quality: "q3" },
  },
  judas: {
    moms_heart:      { item: "Shadow Baby",             wikiFile: "013_baby_shadow.png",                           quality: "coop" },
    isaac:           { item: "Guillotine",              wikiFile: "Collectible_Guillotine_icon.png",               quality: "q2" },
    blue_baby:       { item: "The Left Hand",           wikiFile: "Trinket_The_Left_Hand_icon.png",                quality: "trinket" },
    satan:           { item: "Judas' Tongue",           wikiFile: "Trinket_Judas'_Tongue_icon.png",                quality: "trinket" },
    lamb:            { item: "Curved Horn",             wikiFile: "Trinket_Curved_Horn_icon.png",                  quality: "trinket" },
    mega_satan:      { item: "Brown Baby",              wikiFile: "038_baby_brown.png",                            quality: "coop" },
    boss_rush:       { item: "Judas' Shadow",           wikiFile: "Collectible_Judas'_Shadow_icon.png",            quality: "q3" },
    hush:            { item: "Betrayal",                wikiFile: "Collectible_Betrayal_icon.png",                 quality: "q1" },
    delirium:        { item: "Shade",                   wikiFile: "Collectible_Shade_icon.png",                    quality: "q0" },
    mother:          { item: "Akeldama",                wikiFile: "Collectible_Akeldama_icon.png",                 quality: "q2" },
    beast:           { item: "Redemption",              wikiFile: "Collectible_Redemption_icon.png",               quality: "q2" },
    ultra_greed:     { item: "My Shadow",               wikiFile: "Collectible_My_Shadow_icon.png",                quality: "q2" },
    ultra_greedier:  { item: "Eye of Belial",           wikiFile: "Collectible_Eye_of_Belial_icon.png",            quality: "q3" },
  },
  blue_baby: {
    moms_heart:      { item: "Dead Baby",               wikiFile: "022_baby_dead.png",                             quality: "coop" },
    isaac:           { item: "The D6",                  wikiFile: "Collectible_The_D6_icon.png",                   quality: "q4" },
    blue_baby:       { item: "Fate",                    wikiFile: "Collectible_Fate_icon.png",                     quality: "q3" },
    satan:           { item: "Forget Me Now",           wikiFile: "Collectible_Forget_Me_Now_icon.png",            quality: "q3" },
    lamb:            { item: "???'s Soul",              wikiFile: "Trinket_Blue_Baby's_Soul_icon.png",             quality: "trinket" },
    mega_satan:      { item: "Blue Baby",               wikiFile: "030_baby_blue.png",                             quality: "coop" },
    boss_rush:       { item: "???'s Only Friend",       wikiFile: "Collectible_Blue_Baby's_Only_Friend_icon.png",  quality: "q1" },
    hush:            { item: "Fate's Reward",           wikiFile: "Collectible_Fate's_Reward_icon.png",            quality: "q2" },
    delirium:        { item: "King Baby",               wikiFile: "Collectible_King_Baby_icon.png",                quality: "q1" },
    mother:          { item: "Eternal D6",              wikiFile: "Collectible_Eternal_D6_icon.png",               quality: "q3" },
    beast:           { item: "Montezuma's Revenge",     wikiFile: "Collectible_Montezuma's_Revenge_icon.png",      quality: "q2" },
    ultra_greed:     { item: "Cracked Dice",            wikiFile: "Trinket_Cracked_Dice_icon.png",                 quality: "trinket" },
    ultra_greedier:  { item: "Meconium",                wikiFile: "Trinket_Meconium_icon.png",                     quality: "trinket" },
  },
  eve: {
    moms_heart:      { item: "Crow Baby",               wikiFile: "012_baby_crow.png",                             quality: "coop" },
    isaac:           { item: "Eve's Bird Foot",         wikiFile: "Trinket_Eve's_Bird_Foot_icon.png",              quality: "trinket" },
    blue_baby:       { item: "Sacrificial Dagger",      wikiFile: "Collectible_Sacrificial_Dagger_icon.png",       quality: "q2" },
    satan:           { item: "Razor Blade",             wikiFile: "Collectible_Razor_Blade_icon.png",              quality: "q0" },
    lamb:            { item: "Black Lipstick",          wikiFile: "Trinket_Black_Lipstick_icon.png",               quality: "trinket" },
    mega_satan:      { item: "Lil Baby",                wikiFile: "036_baby_lil.png",                              quality: "coop" },
    boss_rush:       { item: "Eve's Mascara",           wikiFile: "Collectible_Eve's_Mascara_icon.png",            quality: "q3" },
    hush:            { item: "Athame",                  wikiFile: "Collectible_Athame_icon.png",                   quality: "q3" },
    delirium:        { item: "Dull Razor",              wikiFile: "Collectible_Dull_Razor_icon.png",               quality: "q1" },
    mother:          { item: "Bird Cage",               wikiFile: "Collectible_Bird_Cage_icon.png",                quality: "q1" },
    beast:           { item: "Cracked Orb",             wikiFile: "Collectible_Cracked_Orb_icon.png",              quality: "q1" },
    ultra_greed:     { item: "Black Feather",           wikiFile: "Trinket_Black_Feather_icon.png",                quality: "trinket" },
    ultra_greedier:  { item: "Crow Heart",              wikiFile: "Trinket_Crow_Heart_icon.png",                   quality: "trinket" },
  },
  samson: {
    moms_heart:      { item: "Fighting Baby",           wikiFile: "023_baby_fighting.png",                         quality: "coop" },
    isaac:           { item: "Bloody Lust",             wikiFile: "Collectible_Bloody_Lust_icon.png",              quality: "q2" },
    blue_baby:       { item: "Blood Penny",             wikiFile: "Trinket_Bloody_Penny_icon.png",                 quality: "trinket" },
    satan:           { item: "Blood Rights",            wikiFile: "Collectible_Blood_Rights_icon.png",             quality: "q0" },
    lamb:            { item: "Samson's Lock",           wikiFile: "Trinket_Samson's_Lock_icon.png",                quality: "trinket" },
    mega_satan:      { item: "Rage Baby",               wikiFile: "031_baby_rage.png",                             quality: "coop" },
    boss_rush:       { item: "Samson's Chains",         wikiFile: "Collectible_Samson's_Chains_icon.png",          quality: "q1" },
    hush:            { item: "Blind Rage",              wikiFile: "Trinket_Blind_Rage_icon.png",                   quality: "trinket" },
    delirium:        { item: "Bloody Crown",            wikiFile: "Trinket_Bloody_Crown_icon.png",                 quality: "trinket" },
    mother:          { item: "Bloody Gust",             wikiFile: "Collectible_Bloody_Gust_icon.png",              quality: "q2" },
    beast:           { item: "Empty Heart",             wikiFile: "Collectible_Empty_Heart_icon.png",              quality: "q1" },
    ultra_greed:     { item: "Lusty Blood",             wikiFile: "Collectible_Lusty_Blood_icon.png",              quality: "q3" },
    ultra_greedier:  { item: "Stem Cell",               wikiFile: "Trinket_Stem_Cell_icon.png",                    quality: "trinket" },
  },
  azazel: {
    moms_heart:      { item: "Begotten Baby",           wikiFile: "021_baby_begotten.png",                         quality: "coop" },
    isaac:           { item: "Satanic Bible",           wikiFile: "Collectible_Satanic_Bible_icon.png",            quality: "q4" },
    blue_baby:       { item: "Abaddon",                 wikiFile: "Collectible_Abaddon_icon.png",                  quality: "q3" },
    satan:           { item: "Daemon's Tail",           wikiFile: "Trinket_Daemon's_Tail_icon.png",                quality: "trinket" },
    lamb:            { item: "Demon Baby",              wikiFile: "Collectible_Demon_Baby_icon.png",               quality: "q2" },
    mega_satan:      { item: "Black Baby",              wikiFile: "027_baby_black.png",                            quality: "coop" },
    boss_rush:       { item: "The Nail",                wikiFile: "Collectible_The_Nail_icon.png",                 quality: "q2" },
    hush:            { item: "Maw of the Void",         wikiFile: "Collectible_Maw_Of_The_Void_icon.png",          quality: "q3" },
    delirium:        { item: "Dark Prince's Crown",     wikiFile: "Collectible_Dark_Prince's_Crown_icon.png",      quality: "q1" },
    mother:          { item: "Devil's Crown",           wikiFile: "Trinket_Devil's_Crown_icon.png",                quality: "trinket" },
    beast:           { item: "Lil Abaddon",             wikiFile: "Collectible_Lil_Abaddon_icon.png",              quality: "q2" },
    ultra_greed:     { item: "Lilith",                  wikiFile: "Character_Lilith_icon.png",                     quality: "character" },
    ultra_greedier:  { item: "Bat Wing",                wikiFile: "Trinket_Bat_Wing_icon.png",                     quality: "trinket" },
  },
  lazarus: {
    moms_heart:      { item: "Wrapped Baby",            wikiFile: "020_baby_wrapped.png",                          quality: "coop" },
    isaac:           { item: "Lazarus' Rags",           wikiFile: "Collectible_Lazarus'_Rags_icon.png",            quality: "q1" },
    blue_baby:       { item: "Store Credit",            wikiFile: "Trinket_Store_Credit_icon.png",                 quality: "trinket" },
    satan:           { item: "Broken Ankh",             wikiFile: "Trinket_Broken_Ankh_icon.png",                  quality: "trinket" },
    lamb:            { item: "Pandora's Box",           wikiFile: "Collectible_Pandora's_Box_icon.png",            quality: "q2" },
    mega_satan:      { item: "Long Baby",               wikiFile: "034_baby_long.png",                             quality: "coop" },
    boss_rush:       { item: "Missing No.",             wikiFile: "Collectible_Missing_No._icon.png",              quality: "q0" },
    hush:            { item: "Empty Vessel",            wikiFile: "Collectible_Empty_Vessel_icon.png",             quality: "q2" },
    delirium:        { item: "Compound Fracture",       wikiFile: "Collectible_Compound_Fracture_icon.png",        quality: "q3" },
    mother:          { item: "Tinytoma",                wikiFile: "Collectible_Tinytoma_icon.png",                 quality: "q1" },
    beast:           { item: "Astral Projection",       wikiFile: "Collectible_Astral_Projection_icon.png",        quality: "q2" },
    ultra_greed:     { item: "Key Bum",                 wikiFile: "Collectible_Key_Bum_icon.png",                  quality: "q0" },
    ultra_greedier:  { item: "Plan C",                  wikiFile: "Collectible_Plan_C_icon.png",                   quality: "q0" },
  },
  eden: {
    moms_heart:      { item: "Glitch Baby",             wikiFile: "025_baby_glitch.png",                           quality: "coop" },
    isaac:           { item: "Blank Card",              wikiFile: "Collectible_Blank_Card_icon.png",               quality: "q2" },
    blue_baby:       { item: "Mysterious Paper",        wikiFile: "Trinket_Mysterious_Paper_icon.png",             quality: "trinket" },
    satan:           { item: "Book of Secrets",         wikiFile: "Collectible_Book_of_Secrets_icon.png",          quality: "q1" },
    lamb:            { item: "Mystery Sack",            wikiFile: "Collectible_Mystery_Sack_icon.png",             quality: "q2" },
    mega_satan:      { item: "Yellow Baby",             wikiFile: "033_baby_yellow.png",                           quality: "coop" },
    boss_rush:       { item: "Undefined",               wikiFile: "Collectible_Undefined_icon.png",                quality: "q2" },
    hush:            { item: "Eden's Blessing",         wikiFile: "Collectible_Eden's_Blessing_icon.png",          quality: "q3" },
    delirium:        { item: "Eden's Soul",             wikiFile: "Collectible_Eden's_Soul_icon.png",              quality: "q3" },
    mother:          { item: "'M",                      wikiFile: "Trinket_'M_icon.png",                           quality: "trinket" },
    beast:           { item: "Everything Jar",          wikiFile: "Collectible_Everything_Jar_icon.png",           quality: "q3" },
    ultra_greed:     { item: "GB Bug",                  wikiFile: "Collectible_GB_Bug_icon.png",                   quality: "q1" },
    ultra_greedier:  { item: "Metronome",               wikiFile: "Collectible_Metronome_icon.png",                quality: "q1" },
  },
  the_lost: {
    moms_heart:      { item: "-0- Baby",                wikiFile: "024_baby_0.png",                                quality: "coop" },
    isaac:           { item: "Isaac's Heart",           wikiFile: "Collectible_Isaac's_Heart_icon.png",            quality: "q0" },
    blue_baby:       { item: "The Body",                wikiFile: "Collectible_The_Body_icon.png",                 quality: "q3" },
    satan:           { item: "The Mind",                wikiFile: "Collectible_The_Mind_icon.png",                 quality: "q3" },
    lamb:            { item: "The Soul",                wikiFile: "Collectible_The_Soul_icon.png",                 quality: "q3" },
    mega_satan:      { item: "White Baby",              wikiFile: "029_baby_white.png",                            quality: "coop" },
    boss_rush:       { item: "D100",                    wikiFile: "Collectible_D100_icon.png",                     quality: "q3" },
    hush:            { item: "Sworn Protector",         wikiFile: "Collectible_Sworn_Protector_icon.png",          quality: "q3" },
    delirium:        { item: "Holy Card",               wikiFile: "Pickup_Holy_Card_icon.png",                     quality: "consumable" },
    mother:          { item: "Lost Soul",               wikiFile: "Collectible_Lost_Soul_icon.png",                quality: "q2" },
    beast:           { item: "Hungry Soul",             wikiFile: "Collectible_Hungry_Soul_icon.png",              quality: "q2" },
    ultra_greed:     { item: "Zodiac",                  wikiFile: "Collectible_Zodiac_icon.png",                   quality: "q1" },
    ultra_greedier:  { item: "Dad's Lost Coin",         wikiFile: "Collectible_Dad's_Lost_Coin_icon.png",          quality: "q1" },
  },
  lilith: {
    moms_heart:      { item: "Goat Head Baby",          wikiFile: "053_baby_goatbaby.png",                         quality: "coop" },
    isaac:           { item: "Rune Bag",                wikiFile: "Collectible_Rune_Bag_icon.png",                 quality: "q3" },
    blue_baby:       { item: "Cambion Conception",      wikiFile: "Collectible_Cambion_Conception_icon.png",       quality: "q2" },
    satan:           { item: "Serpent's Kiss",          wikiFile: "Collectible_Serpent's_Kiss_icon.png",           quality: "q2" },
    lamb:            { item: "Succubus",                wikiFile: "Collectible_Succubus_icon.png",                 quality: "q3" },
    mega_satan:      { item: "Big Baby",                wikiFile: "037_baby_big.png",                              quality: "coop" },
    boss_rush:       { item: "Immaculate Conception",   wikiFile: "Collectible_Immaculate_Conception_icon.png",    quality: "q1" },
    hush:            { item: "Incubus",                 wikiFile: "Collectible_Incubus_icon.png",                  quality: "q4" },
    delirium:        { item: "Euthanasia",              wikiFile: "Collectible_Euthanasia_icon.png",               quality: "q3" },
    mother:          { item: "Blood Puppy",             wikiFile: "Collectible_Blood_Puppy_icon.png",              quality: "q1" },
    beast:           { item: "C Section",               wikiFile: "Collectible_C_Section_icon.png",                quality: "q4" },
    ultra_greed:     { item: "Box of Friends",          wikiFile: "Collectible_Box_of_Friends_icon.png",           quality: "q1" },
    ultra_greedier:  { item: "Duality",                 wikiFile: "Collectible_Duality_icon.png",                  quality: "q1" },
  },
  keeper: {
    moms_heart:      { item: "Super Greed Baby",        wikiFile: "054_baby_supergreedbaby.png",                   quality: "coop" },
    isaac:           { item: "Wooden Nickel",           wikiFile: "Collectible_Wooden_Nickel_icon.png",            quality: "q1" },
    blue_baby:       { item: "Deep Pockets",            wikiFile: "Collectible_Deep_Pockets_icon.png",             quality: "q2" },
    satan:           { item: "Store Key",               wikiFile: "Trinket_Store_Key_icon.png",                    quality: "trinket" },
    lamb:            { item: "Karma",                   wikiFile: "Trinket_Karma_icon.png",                        quality: "trinket" },
    mega_satan:      { item: "Noose Baby",              wikiFile: "039_baby_noose.png",                            quality: "coop" },
    boss_rush:       { item: "Sticky Nickels",          wikiFile: "Achievement_Sticky_Nickels_icon.png",           quality: "consumable" },
    hush:            { item: "1 More Coin Heart",       wikiFile: "HUD_heart_coin_full.png",                       quality: "consumable" },
    delirium:        { item: "Crooked Penny",           wikiFile: "Collectible_Crooked_Penny_icon.png",            quality: "q2" },
    mother:          { item: "Keeper's Sack",           wikiFile: "Collectible_Keeper's_Sack_icon.png",            quality: "q3" },
    beast:           { item: "Keeper's Box",            wikiFile: "Collectible_Keeper's_Box_icon.png",             quality: "q2" },
    ultra_greed:     { item: "Rib of Greed",            wikiFile: "Trinket_Rib_of_Greed_icon.png",                 quality: "trinket" },
    ultra_greedier:  { item: "Eye of Greed",            wikiFile: "Collectible_Eye_of_Greed_icon.png",             quality: "q2" },
  },
  apollyon: {
    moms_heart:      { item: "Smelter",                 wikiFile: "Collectible_Smelter_icon.png",                  quality: "q2" },
    isaac:           { item: "Locust of War",           wikiFile: "Trinket_Locust_of_War_icon.png",                quality: "trinket" },
    blue_baby:       { item: "Locust of Famine",        wikiFile: "Trinket_Locust_of_Famine_icon.png",             quality: "trinket" },
    satan:           { item: "Locust of Pestilence",    wikiFile: "Trinket_Locust_of_Pestilence_icon.png",         quality: "trinket" },
    lamb:            { item: "Locust of Death",         wikiFile: "Trinket_Locust_of_Death_icon.png",              quality: "trinket" },
    mega_satan:      { item: "Mort Baby",               wikiFile: "055_baby_mort.png",                             quality: "coop" },
    boss_rush:       { item: "Locust of Conquest",      wikiFile: "Trinket_Locust_of_Conquest_icon.png",           quality: "trinket" },
    hush:            { item: "Hushy",                   wikiFile: "Collectible_Hushy_icon.png",                    quality: "q0" },
    delirium:        { item: "Void",                    wikiFile: "Collectible_Void_icon.png",                     quality: "q4" },
    mother:          { item: "Lil Portal",              wikiFile: "Collectible_Lil_Portal_icon.png",               quality: "q1" },
    beast:           { item: "Worm Friend",             wikiFile: "Collectible_Worm_Friend_icon.png",              quality: "q3" },
    ultra_greed:     { item: "Brown Nugget",            wikiFile: "Collectible_Brown_Nugget_icon.png",             quality: "q0" },
    ultra_greedier:  { item: "Black Rune",              wikiFile: "Pickup_Black_Rune_icon.png",                    quality: "consumable" },
  },
  the_forgotten: {
    moms_heart:      { item: "Marrow",                  wikiFile: "Collectible_Marrow_icon.png",                   quality: "q1" },
    isaac:           { item: "Slipped Rib",             wikiFile: "Collectible_Slipped_Rib_icon.png",              quality: "q2" },
    blue_baby:       { item: "Jaw Bone",                wikiFile: "Collectible_Jaw_Bone_icon.png",                 quality: "q1" },
    satan:           { item: "Pointy Rib",              wikiFile: "Collectible_Pointy_Rib_icon.png",               quality: "q2" },
    lamb:            { item: "Brittle Bones",           wikiFile: "Collectible_Brittle_Bones_icon.png",            quality: "q3" },
    mega_satan:      { item: "Bound Baby",              wikiFile: "058_baby_bound.png",                            quality: "coop" },
    boss_rush:       { item: "Divorce Papers",          wikiFile: "Collectible_Divorce_Papers_icon.png",           quality: "q3" },
    hush:            { item: "Hallowed Ground",         wikiFile: "Collectible_Hallowed_Ground_icon.png",          quality: "q1" },
    delirium:        { item: "Book of the Dead",        wikiFile: "Collectible_Book_of_the_Dead_icon.png",         quality: "q3" },
    mother:          { item: "Bone Spurs",              wikiFile: "Collectible_Bone_Spurs_icon.png",               quality: "q2" },
    beast:           { item: "Spirit Shackles",         wikiFile: "Collectible_Spirit_Shackles_icon.png",          quality: "q2" },
    ultra_greed:     { item: "Finger Bone",             wikiFile: "Trinket_Finger_Bone_icon.png",                  quality: "trinket" },
    ultra_greedier:  { item: "Dad's Ring",              wikiFile: "Collectible_Dad's_Ring_icon.png",               quality: "q3" },
  },
  bethany: {
    moms_heart:      { item: "Wisp Baby",               wikiFile: "064_baby_wisp.png",                             quality: "coop" },
    isaac:           { item: "Book of Virtues",         wikiFile: "Collectible_Book_of_Virtues_icon.png",          quality: "q3" },
    blue_baby:       { item: "Blessed Penny",           wikiFile: "Trinket_Blessed_Penny_icon.png",                quality: "trinket" },
    satan:           { item: "Urn of Souls",            wikiFile: "Collectible_Urn_of_Souls_icon.png",             quality: "q3" },
    lamb:            { item: "Alabaster Box",           wikiFile: "Collectible_Alabaster_Box_icon.png",            quality: "q2" },
    mega_satan:      { item: "Glowing Baby",            wikiFile: "066_baby_glowing.png",                          quality: "coop" },
    boss_rush:       { item: "Beth's Faith",            wikiFile: "Trinket_Beth's_Faith_icon.png",                 quality: "trinket" },
    hush:            { item: "Divine Intervention",     wikiFile: "Collectible_Divine_Intervention_icon.png",      quality: "q2" },
    delirium:        { item: "Star of Bethlehem",       wikiFile: "Collectible_Star_of_Bethlehem_icon.png",        quality: "q3" },
    mother:          { item: "Revelation",              wikiFile: "Collectible_Revelation_icon.png",               quality: "q4" },
    beast:           { item: "Jar of Wisps",            wikiFile: "Collectible_Jar_of_Wisps_icon.png",             quality: "q2" },
    ultra_greed:     { item: "Soul Locket",             wikiFile: "Collectible_Soul_Locket_icon.png",              quality: "q1" },
    ultra_greedier:  { item: "Vade Retro",              wikiFile: "Collectible_Vade_Retro_icon.png",               quality: "q2" },
  },
  jacob_esau: {
    moms_heart:      { item: "Double Baby",             wikiFile: "065_baby_double.png",                           quality: "coop" },
    isaac:           { item: "The Stairway",            wikiFile: "Collectible_The_Stairway_icon.png",             quality: "q3" },
    blue_baby:       { item: "Birthright",              wikiFile: "Collectible_Birthright_icon.png",               quality: "q3" },
    satan:           { item: "Red Stew",                wikiFile: "Collectible_Red_Stew_icon.png",                 quality: "q2" },
    lamb:            { item: "Damocles",                wikiFile: "Collectible_Damocles_icon.png",                 quality: "q2" },
    mega_satan:      { item: "Illusion Baby",           wikiFile: "067_baby_illusion.png",                         quality: "coop" },
    boss_rush:       { item: "Rock Bottom",             wikiFile: "Collectible_Rock_Bottom_icon.png",              quality: "q3" },
    hush:            { item: "Vanishing Twin",          wikiFile: "Collectible_Vanishing_Twin_icon.png",           quality: "q2" },
    delirium:        { item: "Suplex!",                 wikiFile: "Collectible_Suplex!_icon.png",                  quality: "q2" },
    mother:          { item: "Magic Skin",              wikiFile: "Collectible_Magic_Skin_icon.png",               quality: "q2" },
    beast:           { item: "Friend Finder",           wikiFile: "Collectible_Friend_Finder_icon.png",            quality: "q3" },
    ultra_greed:     { item: "Inner Child",             wikiFile: "Collectible_Inner_Child_icon.png",              quality: "q2" },
    ultra_greedier:  { item: "Genesis",                 wikiFile: "Collectible_Genesis_icon.png",                  quality: "q3" },
  },
  t_isaac: {
    isaac:           { item: "Mom's Lock",              wikiFile: "Trinket_Mom's_Lock_icon.png",                   quality: "trinket" },
    blue_baby:       { item: "Mom's Lock",              wikiFile: "Trinket_Mom's_Lock_icon.png",                   quality: "trinket" },
    satan:           { item: "Mom's Lock",              wikiFile: "Trinket_Mom's_Lock_icon.png",                   quality: "trinket" },
    lamb:            { item: "Mom's Lock",              wikiFile: "Trinket_Mom's_Lock_icon.png",                   quality: "trinket" },
    mega_satan:      { item: "Mega Chest",              wikiFile: "Mega_Chest.png",                                quality: "feature" },
    boss_rush:       { item: "Soul of Isaac",           wikiFile: "Pickup_Soul_of_Isaac_icon.png",                 quality: "consumable" },
    hush:            { item: "Soul of Isaac",           wikiFile: "Pickup_Soul_of_Isaac_icon.png",                 quality: "consumable" },
    delirium:        { item: "Spindown Dice",           wikiFile: "Collectible_Spindown_Dice_icon.png",            quality: "q4" },
    mother:          { item: "Dice Bag",                wikiFile: "Trinket_Dice_Bag_icon.png",                     quality: "trinket" },
    beast:           { item: "Glitched Crown",          wikiFile: "Collectible_Glitched_Crown_icon.png",           quality: "q4" },
    ultra_greedier:  { item: "The Stars?",              wikiFile: "Pickup_XVII_-_Inverted_The_Stars_icon.png",     quality: "consumable" },
  },
  t_magdalene: {
    isaac:           { item: "Holy Crown",              wikiFile: "Trinket_Holy_Crown_icon.png",                   quality: "trinket" },
    blue_baby:       { item: "Holy Crown",              wikiFile: "Trinket_Holy_Crown_icon.png",                   quality: "trinket" },
    satan:           { item: "Holy Crown",              wikiFile: "Trinket_Holy_Crown_icon.png",                   quality: "trinket" },
    lamb:            { item: "Holy Crown",              wikiFile: "Trinket_Holy_Crown_icon.png",                   quality: "trinket" },
    mega_satan:      { item: "Queen of Hearts",         wikiFile: "Pickup_Queen_of_Hearts_icon.png",               quality: "consumable" },
    boss_rush:       { item: "Soul of Magdalene",       wikiFile: "Pickup_Soul_of_Magdalene_icon.png",             quality: "consumable" },
    hush:            { item: "Soul of Magdalene",       wikiFile: "Pickup_Soul_of_Magdalene_icon.png",             quality: "consumable" },
    delirium:        { item: "Hypercoagulation",        wikiFile: "Collectible_Hypercoagulation_icon.png",         quality: "q2" },
    mother:          { item: "Mother's Kiss",           wikiFile: "Trinket_Mother's_Kiss_icon.png",                quality: "trinket" },
    beast:           { item: "Belly Jelly",             wikiFile: "Collectible_Belly_Jelly_icon.png",              quality: "q3" },
    ultra_greedier:  { item: "The Lovers?",             wikiFile: "Pickup_VI_-_Inverted_The_Lovers_icon.png",      quality: "consumable" },
  },
  t_cain: {
    isaac:           { item: "Gilded Key",              wikiFile: "Trinket_Gilded_Key_icon.png",                   quality: "trinket" },
    blue_baby:       { item: "Gilded Key",              wikiFile: "Trinket_Gilded_Key_icon.png",                   quality: "trinket" },
    satan:           { item: "Gilded Key",              wikiFile: "Trinket_Gilded_Key_icon.png",                   quality: "trinket" },
    lamb:            { item: "Gilded Key",              wikiFile: "Trinket_Gilded_Key_icon.png",                   quality: "trinket" },
    mega_satan:      { item: "Gold Pills",              wikiFile: "Achievement_Gold_Pill_icon.png",                quality: "consumable" },
    boss_rush:       { item: "Soul of Cain",            wikiFile: "Pickup_Soul_of_Cain_icon.png",                  quality: "consumable" },
    hush:            { item: "Soul of Cain",            wikiFile: "Pickup_Soul_of_Cain_icon.png",                  quality: "consumable" },
    delirium:        { item: "Bag of Crafting",         wikiFile: "Collectible_Bag_of_Crafting_icon.png",          quality: "q3" },
    mother:          { item: "Lucky Sack",              wikiFile: "Trinket_Lucky_Sack_icon.png",                   quality: "trinket" },
    beast:           { item: "Blue Key",                wikiFile: "Trinket_Blue_Key_icon.png",                     quality: "trinket" },
    ultra_greedier:  { item: "Wheel of Fortune?",       wikiFile: "Pickup_X_-_Inverted_Wheel_of_Fortune_icon.png", quality: "consumable" },
  },
  t_judas: {
    isaac:           { item: "Your Soul",               wikiFile: "Trinket_Your_Soul_icon.png",                    quality: "trinket" },
    blue_baby:       { item: "Your Soul",               wikiFile: "Trinket_Your_Soul_icon.png",                    quality: "trinket" },
    satan:           { item: "Your Soul",               wikiFile: "Trinket_Your_Soul_icon.png",                    quality: "trinket" },
    lamb:            { item: "Your Soul",               wikiFile: "Trinket_Your_Soul_icon.png",                    quality: "trinket" },
    mega_satan:      { item: "Black Sack",              wikiFile: "Black_Sack.png",                                quality: "feature" },
    boss_rush:       { item: "Soul of Judas",           wikiFile: "Pickup_Soul_of_Judas_icon.png",                 quality: "consumable" },
    hush:            { item: "Soul of Judas",           wikiFile: "Pickup_Soul_of_Judas_icon.png",                 quality: "consumable" },
    delirium:        { item: "Dark Arts",               wikiFile: "Collectible_Dark_Arts_icon.png",                quality: "q2" },
    mother:          { item: "Number Magnet",           wikiFile: "Trinket_Number_Magnet_icon.png",                quality: "trinket" },
    beast:           { item: "Sanguine Bond",           wikiFile: "Collectible_Sanguine_Bond_icon.png",            quality: "q1" },
    ultra_greedier:  { item: "The Magician?",           wikiFile: "Pickup_I_-_Inverted_The_Magician_icon.png",     quality: "consumable" },
  },
  t_blue_baby: {
    isaac:           { item: "Dingle Berry",            wikiFile: "Trinket_Dingle_Berry_icon.png",                 quality: "trinket" },
    blue_baby:       { item: "Dingle Berry",            wikiFile: "Trinket_Dingle_Berry_icon.png",                 quality: "trinket" },
    satan:           { item: "Dingle Berry",            wikiFile: "Trinket_Dingle_Berry_icon.png",                 quality: "trinket" },
    lamb:            { item: "Dingle Berry",            wikiFile: "Trinket_Dingle_Berry_icon.png",                 quality: "trinket" },
    mega_satan:      { item: "Charming Poop",           wikiFile: "Charming_Poop.png",                             quality: "feature" },
    boss_rush:       { item: "Soul of Blue Baby",       wikiFile: "Pickup_Soul_of_???_icon.png",                   quality: "consumable" },
    hush:            { item: "Soul of Blue Baby",       wikiFile: "Pickup_Soul_of_???_icon.png",                   quality: "consumable" },
    delirium:        { item: "IBS",                     wikiFile: "Collectible_IBS_icon.png",                      quality: "q0" },
    mother:          { item: "Ring Cap",                wikiFile: "Trinket_Ring_Cap_icon.png",                     quality: "trinket" },
    beast:           { item: "The Swarm",               wikiFile: "Collectible_The_Swarm_icon.png",                quality: "q2" },
    ultra_greedier:  { item: "The Emperor?",            wikiFile: "Pickup_IV_-_Inverted_The_Emperor_icon.png",     quality: "consumable" },
  },
  t_eve: {
    isaac:           { item: "Strange Key",             wikiFile: "Trinket_Strange_Key_icon.png",                  quality: "trinket" },
    blue_baby:       { item: "Strange Key",             wikiFile: "Trinket_Strange_Key_icon.png",                  quality: "trinket" },
    satan:           { item: "Strange Key",             wikiFile: "Trinket_Strange_Key_icon.png",                  quality: "trinket" },
    lamb:            { item: "Strange Key",             wikiFile: "Trinket_Strange_Key_icon.png",                  quality: "trinket" },
    mega_satan:      { item: "Horse Pills",             wikiFile: "Achievement_Horse_Pill_icon.png",               quality: "consumable" },
    boss_rush:       { item: "Soul of Eve",             wikiFile: "Pickup_Soul_of_Eve_icon.png",                   quality: "consumable" },
    hush:            { item: "Soul of Eve",             wikiFile: "Pickup_Soul_of_Eve_icon.png",                   quality: "consumable" },
    delirium:        { item: "Sumptorium",              wikiFile: "Collectible_Sumptorium_icon.png",               quality: "q3" },
    mother:          { item: "Lil Clot",                wikiFile: "Trinket_Lil_Clot_icon.png",                     quality: "trinket" },
    beast:           { item: "Heartbreak",              wikiFile: "Collectible_Heartbreak_icon.png",               quality: "q3" },
    ultra_greedier:  { item: "The Empress?",            wikiFile: "Pickup_III_-_Inverted_The_Empress_icon.png",    quality: "consumable" },
  },
  t_samson: {
    isaac:           { item: "Temporary Tattoo",        wikiFile: "Trinket_Temporary_Tattoo_icon.png",             quality: "trinket" },
    blue_baby:       { item: "Temporary Tattoo",        wikiFile: "Trinket_Temporary_Tattoo_icon.png",             quality: "trinket" },
    satan:           { item: "Temporary Tattoo",        wikiFile: "Trinket_Temporary_Tattoo_icon.png",             quality: "trinket" },
    lamb:            { item: "Temporary Tattoo",        wikiFile: "Trinket_Temporary_Tattoo_icon.png",             quality: "trinket" },
    mega_satan:      { item: "Crane Game",              wikiFile: "Crane_Game.png",                                quality: "feature" },
    boss_rush:       { item: "Soul of Samson",          wikiFile: "Pickup_Soul_of_Samson_icon.png",                quality: "consumable" },
    hush:            { item: "Soul of Samson",          wikiFile: "Pickup_Soul_of_Samson_icon.png",                quality: "consumable" },
    delirium:        { item: "Berserk!",                wikiFile: "Collectible_Berserk!_icon.png",                 quality: "q2" },
    mother:          { item: "Swallowed M80",           wikiFile: "Trinket_Swallowed_M80_icon.png",                quality: "trinket" },
    beast:           { item: "Larynx",                  wikiFile: "Collectible_Larynx_icon.png",                   quality: "q2" },
    ultra_greedier:  { item: "Strength?",               wikiFile: "Pickup_XI_-_Inverted_Strength_icon.png",        quality: "consumable" },
  },
  t_azazel: {
    isaac:           { item: "Wicked Crown",            wikiFile: "Trinket_Wicked_Crown_icon.png",                 quality: "trinket" },
    blue_baby:       { item: "Wicked Crown",            wikiFile: "Trinket_Wicked_Crown_icon.png",                 quality: "trinket" },
    satan:           { item: "Wicked Crown",            wikiFile: "Trinket_Wicked_Crown_icon.png",                 quality: "trinket" },
    lamb:            { item: "Wicked Crown",            wikiFile: "Trinket_Wicked_Crown_icon.png",                 quality: "trinket" },
    mega_satan:      { item: "Hell Game",               wikiFile: "Hell_Game.png",                                 quality: "feature" },
    boss_rush:       { item: "Soul of Azazel",          wikiFile: "Pickup_Soul_of_Azazel_icon.png",                quality: "consumable" },
    hush:            { item: "Soul of Azazel",          wikiFile: "Pickup_Soul_of_Azazel_icon.png",                quality: "consumable" },
    delirium:        { item: "Hemoptysis",              wikiFile: "Collectible_Hemoptysis_icon.png",               quality: "q1" },
    mother:          { item: "Azazel's Stump",          wikiFile: "Trinket_Azazel's_Stump_icon.png",               quality: "trinket" },
    beast:           { item: "Azazel's Rage",           wikiFile: "Collectible_Azazel's_Rage_icon.png",            quality: "q2" },
    ultra_greedier:  { item: "The Devil?",              wikiFile: "Pickup_XV_-_Inverted_The_Devil_icon.png",       quality: "consumable" },
  },
  t_lazarus: {
    isaac:           { item: "Torn Pocket",             wikiFile: "Trinket_Torn_Pocket_icon.png",                  quality: "trinket" },
    blue_baby:       { item: "Torn Pocket",             wikiFile: "Trinket_Torn_Pocket_icon.png",                  quality: "trinket" },
    satan:           { item: "Torn Pocket",             wikiFile: "Trinket_Torn_Pocket_icon.png",                  quality: "trinket" },
    lamb:            { item: "Torn Pocket",             wikiFile: "Trinket_Torn_Pocket_icon.png",                  quality: "trinket" },
    mega_satan:      { item: "Wooden Chest",            wikiFile: "Wooden_Chest.png",                              quality: "feature" },
    boss_rush:       { item: "Soul of Lazarus",         wikiFile: "Pickup_Soul_of_Lazarus_icon.png",               quality: "consumable" },
    hush:            { item: "Soul of Lazarus",         wikiFile: "Pickup_Soul_of_Lazarus_icon.png",               quality: "consumable" },
    delirium:        { item: "Flip",                    wikiFile: "Collectible_Flip_icon.png",                     quality: "q4" },
    mother:          { item: "Torn Card",               wikiFile: "Trinket_Torn_Card_icon.png",                    quality: "trinket" },
    beast:           { item: "Salvation",               wikiFile: "Collectible_Salvation_icon.png",                quality: "q3" },
    ultra_greedier:  { item: "Judgement?",              wikiFile: "Pickup_XX_-_Inverted_Judgement_icon.png",       quality: "consumable" },
  },
  t_eden: {
    isaac:           { item: "Nuh Uh!",                 wikiFile: "Trinket_Nuh_Uh!_icon.png",                      quality: "trinket" },
    blue_baby:       { item: "Nuh Uh!",                 wikiFile: "Trinket_Nuh_Uh!_icon.png",                      quality: "trinket" },
    satan:           { item: "Nuh Uh!",                 wikiFile: "Trinket_Nuh_Uh!_icon.png",                      quality: "trinket" },
    lamb:            { item: "Nuh Uh!",                 wikiFile: "Trinket_Nuh_Uh!_icon.png",                      quality: "trinket" },
    mega_satan:      { item: "Wild Card",               wikiFile: "Pickup_Wild_Card_icon.png",                     quality: "consumable" },
    boss_rush:       { item: "Soul of Eden",            wikiFile: "Pickup_Soul_of_Eden_icon.png",                  quality: "consumable" },
    hush:            { item: "Soul of Eden",            wikiFile: "Pickup_Soul_of_Eden_icon.png",                  quality: "consumable" },
    delirium:        { item: "Corrupted Data",          wikiFile: "Achievement_Corrupted_Data_icon.png",           quality: "feature" },
    mother:          { item: "Modeling Clay",           wikiFile: "Trinket_Modeling_Clay_icon.png",                quality: "trinket" },
    beast:           { item: "TMTRAINER",               wikiFile: "Collectible_TMTRAINER_icon.png",                quality: "q0" },
    ultra_greedier:  { item: "The World?",              wikiFile: "Pickup_XXI_-_Inverted_The_World_icon.png",      quality: "consumable" },
  },
  t_lost: {
    isaac:           { item: "Kid's Drawing",           wikiFile: "Trinket_Kid's_Drawing_icon.png",                quality: "trinket" },
    blue_baby:       { item: "Kid's Drawing",           wikiFile: "Trinket_Kid's_Drawing_icon.png",                quality: "trinket" },
    satan:           { item: "Kid's Drawing",           wikiFile: "Trinket_Kid's_Drawing_icon.png",                quality: "trinket" },
    lamb:            { item: "Kid's Drawing",           wikiFile: "Trinket_Kid's_Drawing_icon.png",                quality: "trinket" },
    mega_satan:      { item: "Haunted Chest",           wikiFile: "Haunted_Chest.png",                             quality: "feature" },
    boss_rush:       { item: "Soul of the Lost",        wikiFile: "Pickup_Soul_of_the_Lost_icon.png",              quality: "consumable" },
    hush:            { item: "Soul of the Lost",        wikiFile: "Pickup_Soul_of_the_Lost_icon.png",              quality: "consumable" },
    delirium:        { item: "Ghost Bombs",             wikiFile: "Collectible_Ghost_Bombs_icon.png",              quality: "q2" },
    mother:          { item: "Crystal Key",             wikiFile: "Trinket_Crystal_Key_icon.png",                  quality: "trinket" },
    beast:           { item: "Sacred Orb",              wikiFile: "Collectible_Sacred_Orb_icon.png",               quality: "q4" },
    ultra_greedier:  { item: "The Fool?",               wikiFile: "Pickup_0_-_Inverted_The_Fool_icon.png",         quality: "consumable" },
  },
  t_lilith: {
    isaac:           { item: "The Twins",               wikiFile: "Trinket_The_Twins_icon.png",                    quality: "trinket" },
    blue_baby:       { item: "The Twins",               wikiFile: "Trinket_The_Twins_icon.png",                    quality: "trinket" },
    satan:           { item: "The Twins",               wikiFile: "Trinket_The_Twins_icon.png",                    quality: "trinket" },
    lamb:            { item: "The Twins",               wikiFile: "Trinket_The_Twins_icon.png",                    quality: "trinket" },
    mega_satan:      { item: "Fool's Gold",             wikiFile: "Achievement_Fool's_Gold_icon.png",              quality: "feature" },
    boss_rush:       { item: "Soul of Lilith",          wikiFile: "Pickup_Soul_of_Lilith_icon.png",                quality: "consumable" },
    hush:            { item: "Soul of Lilith",          wikiFile: "Pickup_Soul_of_Lilith_icon.png",                quality: "consumable" },
    delirium:        { item: "Gello",                   wikiFile: "Collectible_Gello_icon.png",                    quality: "q3" },
    mother:          { item: "Adoption Papers",         wikiFile: "Trinket_Adoption_Papers_icon.png",              quality: "trinket" },
    beast:           { item: "Twisted Pair",            wikiFile: "Collectible_Twisted_Pair_icon.png",             quality: "q4" },
    ultra_greedier:  { item: "The High Priestess?",     wikiFile: "Pickup_II_-_Inverted_The_High_Priestess_icon.png", quality: "consumable" },
  },
  t_keeper: {
    isaac:           { item: "Keeper's Bargain",        wikiFile: "Trinket_Keeper's_Bargain_icon.png",             quality: "trinket" },
    blue_baby:       { item: "Keeper's Bargain",        wikiFile: "Trinket_Keeper's_Bargain_icon.png",             quality: "trinket" },
    satan:           { item: "Keeper's Bargain",        wikiFile: "Trinket_Keeper's_Bargain_icon.png",             quality: "trinket" },
    lamb:            { item: "Keeper's Bargain",        wikiFile: "Trinket_Keeper's_Bargain_icon.png",             quality: "trinket" },
    mega_satan:      { item: "Golden Pennies",          wikiFile: "Golden_Penny.png",                              quality: "feature" },
    boss_rush:       { item: "Soul of the Keeper",      wikiFile: "Pickup_Soul_of_the_Keeper_icon.png",            quality: "consumable" },
    hush:            { item: "Soul of the Keeper",      wikiFile: "Pickup_Soul_of_the_Keeper_icon.png",            quality: "consumable" },
    delirium:        { item: "Keeper's Kin",            wikiFile: "Collectible_Keeper's_Kin_icon.png",             quality: "q2" },
    mother:          { item: "Cursed Penny",            wikiFile: "Trinket_Cursed_Penny_icon.png",                 quality: "trinket" },
    beast:           { item: "Strawman",                wikiFile: "Collectible_Strawman_icon.png",                 quality: "q2" },
    ultra_greedier:  { item: "The Hanged Man?",         wikiFile: "Pickup_XII_-_Inverted_The_Hanged_Man_icon.png", quality: "consumable" },
  },
  t_apollyon: {
    isaac:           { item: "Cricket Leg",             wikiFile: "Trinket_Cricket_Leg_icon.png",                  quality: "trinket" },
    blue_baby:       { item: "Cricket Leg",             wikiFile: "Trinket_Cricket_Leg_icon.png",                  quality: "trinket" },
    satan:           { item: "Cricket Leg",             wikiFile: "Trinket_Cricket_Leg_icon.png",                  quality: "trinket" },
    lamb:            { item: "Cricket Leg",             wikiFile: "Trinket_Cricket_Leg_icon.png",                  quality: "trinket" },
    mega_satan:      { item: "Rotten Beggar",           wikiFile: "Rotten_Beggar.png",                             quality: "feature" },
    boss_rush:       { item: "Soul of Apollyon",        wikiFile: "Pickup_Soul_of_Apollyon_icon.png",              quality: "consumable" },
    hush:            { item: "Soul of Apollyon",        wikiFile: "Pickup_Soul_of_Apollyon_icon.png",              quality: "consumable" },
    delirium:        { item: "Abyss",                   wikiFile: "Collectible_Abyss_icon.png",                    quality: "q4" },
    mother:          { item: "Apollyon's Best Friend",  wikiFile: "Trinket_Apollyon's_Best_Friend_icon.png",       quality: "trinket" },
    beast:           { item: "Echo Chamber",            wikiFile: "Collectible_Echo_Chamber_icon.png",             quality: "q3" },
    ultra_greedier:  { item: "The Tower?",              wikiFile: "Pickup_XVI_-_Inverted_The_Tower_icon.png",      quality: "consumable" },
  },
  t_forgotten: {
    isaac:           { item: "Polished Bone",           wikiFile: "Trinket_Polished_Bone_icon.png",                quality: "trinket" },
    blue_baby:       { item: "Polished Bone",           wikiFile: "Trinket_Polished_Bone_icon.png",                quality: "trinket" },
    satan:           { item: "Polished Bone",           wikiFile: "Trinket_Polished_Bone_icon.png",                quality: "trinket" },
    lamb:            { item: "Polished Bone",           wikiFile: "Trinket_Polished_Bone_icon.png",                quality: "trinket" },
    mega_satan:      { item: "Golden Batteries",        wikiFile: "Golden_Battery.png",                            quality: "feature" },
    boss_rush:       { item: "Soul of the Forgotten",   wikiFile: "Pickup_Soul_of_the_Forgotten_icon.png",         quality: "consumable" },
    hush:            { item: "Soul of the Forgotten",   wikiFile: "Pickup_Soul_of_the_Forgotten_icon.png",         quality: "consumable" },
    delirium:        { item: "Decap Attack",            wikiFile: "Collectible_Decap_Attack_icon.png",             quality: "q2" },
    mother:          { item: "Hollow Heart",            wikiFile: "Trinket_Hollow_Heart_icon.png",                 quality: "trinket" },
    beast:           { item: "Isaac's Tomb",            wikiFile: "Collectible_Isaac's_Tomb_icon.png",             quality: "q3" },
    ultra_greedier:  { item: "Death?",                  wikiFile: "Pickup_XIII_-_Inverted_Death_icon.png",         quality: "consumable" },
  },
  t_bethany: {
    isaac:           { item: "Expansion Pack",          wikiFile: "Trinket_Expansion_Pack_icon.png",               quality: "trinket" },
    blue_baby:       { item: "Expansion Pack",          wikiFile: "Trinket_Expansion_Pack_icon.png",               quality: "trinket" },
    satan:           { item: "Expansion Pack",          wikiFile: "Trinket_Expansion_Pack_icon.png",               quality: "trinket" },
    lamb:            { item: "Expansion Pack",          wikiFile: "Trinket_Expansion_Pack_icon.png",               quality: "trinket" },
    mega_satan:      { item: "Confessional",            wikiFile: "Confessional.png",                              quality: "feature" },
    boss_rush:       { item: "Soul of Bethany",         wikiFile: "Pickup_Soul_of_Bethany_icon.png",               quality: "consumable" },
    hush:            { item: "Soul of Bethany",         wikiFile: "Pickup_Soul_of_Bethany_icon.png",               quality: "consumable" },
    delirium:        { item: "Lemegeton",               wikiFile: "Collectible_Lemegeton_icon.png",                quality: "q3" },
    mother:          { item: "Beth's Essence",          wikiFile: "Trinket_Beth's_Essence_icon.png",               quality: "trinket" },
    beast:           { item: "Vengeful Spirit",         wikiFile: "Collectible_Vengeful_Spirit_icon.png",          quality: "q1" },
    ultra_greedier:  { item: "The Hierophant?",         wikiFile: "Pickup_V_-_Inverted_The_Hierophant_icon.png",   quality: "consumable" },
  },
  t_jacob: {
    isaac:           { item: "RC Remote",               wikiFile: "Trinket_RC_Remote_icon.png",                    quality: "trinket" },
    blue_baby:       { item: "RC Remote",               wikiFile: "Trinket_RC_Remote_icon.png",                    quality: "trinket" },
    satan:           { item: "RC Remote",               wikiFile: "Trinket_RC_Remote_icon.png",                    quality: "trinket" },
    lamb:            { item: "RC Remote",               wikiFile: "Trinket_RC_Remote_icon.png",                    quality: "trinket" },
    mega_satan:      { item: "Golden Trinkets",         wikiFile: "Achievement_Golden_Trinket_icon.png",           quality: "feature" },
    boss_rush:       { item: "Soul of Jacob and Esau",  wikiFile: "Pickup_Soul_of_Jacob_and_Esau_icon.png",        quality: "consumable" },
    hush:            { item: "Soul of Jacob and Esau",  wikiFile: "Pickup_Soul_of_Jacob_and_Esau_icon.png",        quality: "consumable" },
    delirium:        { item: "Anima Sola",              wikiFile: "Collectible_Anima_Sola_icon.png",               quality: "q3" },
    mother:          { item: "Found Soul",              wikiFile: "Trinket_Found_Soul_icon.png",                   quality: "trinket" },
    beast:           { item: "Esau Jr.",                wikiFile: "Collectible_Esau_Jr._icon.png",                 quality: "q2" },
    ultra_greedier:  { item: "The Sun? & The Moon?",    wikiFile: "Pickup_XIX_-_Inverted_The_Sun_icon.png",        quality: "consumable" },
  },
};

/** Local sprite slug for an unlock's wiki file — mirrors scripts/scrape-assets.ts. */
export function itemSlug(wikiFile: string): string {
  return wikiFile.replace(/\.png$/i, "").replace(/[^a-z0-9]+/gi, "_").toLowerCase();
}
